### ISSUE TITLE
Training Question

### ISSUE THREAD

**Issue by YOLO6995** [FlorentinBieder/PatchDDM-3D#1]
Hello, you are very good at this job. As a newbie, I would like to ask you for advice. While training using your code I always get the following errors：
![question1](https://github.com/FlorentinBieder/PatchDDM-3D/assets/130556935/e9948276-1ca9-4cc6-bc85-0d5f2d3b6699)

**Comment by FlorentinBieder** [comment]
Please excuse the delay: It looks like you something regarding the half-precision (fp16) went wrong. I'd try to enable or disable it completely. Here the input seems to be in half precision while the network is still in full precision, so there might be a conflict.
