### ISSUE TITLE
processed dataset

### ISSUE THREAD

**Issue by CNGaoWenbo** [FlorentinBieder/PatchDDM-3D#2]
nice work. Could you share the preprocessed dataset or codes? thanks!

**Comment by FlorentinBieder** [comment]
thank you! Unfortunately we are not allowed to share the dataset as we are bound by the usage agreement. We cannot share the preprocessing code, but it should be rather straightforward to rebuild and is described under Section 3 in the paper. Note that the padding is already implemented in the __getitem__() method of the Dataset. The only two other things left to do are the normalization of the foreground as described in the paper, and the file structure described in README.md. Let me know if you have any further questions!

**Comment by CNGaoWenbo** [comment]
understood, thank you
