### ISSUE TITLE
config for training 3D volumes

### ISSUE THREAD

**Issue by CNGaoWenbo** [FlorentinBieder/PatchDDM-3D#3]
Hi, I found the dims=2 in the function "create model". if training on 3D volumes instead of 2D slices, should this be 3? thx

**Comment by pyscorcher** [comment]
That is correct! You can also find the full configuration we used in `run.sh`.

**Comment by FlorentinBieder** [comment]
That is correct! You can find the full configuration we used in `run.sh`.

**Comment by CNGaoWenbo** [comment]
got it. thank you!
